# -*- coding: utf-8 -*-
# Deployment settings for O-Demo_8_MagicDoor.
# This file is autogenerated by the mkb system and used by the s3e deployment
# tool during the build process.

config = {}
cmdline = ['C:/Marmalade/6.2/s3e/makefile_builder/mkb.py', 'c:/Users/1106786/Dropbox/Dropbox/PG life/Project Impact/Code/Demos/O-Demo_8_MagicDoor/O-Demo_8_MagicDoor.mkb', '--deploy-only']
mkb = 'c:/Users/1106786/Dropbox/Dropbox/PG life/Project Impact/Code/Demos/O-Demo_8_MagicDoor/O-Demo_8_MagicDoor.mkb'
mkf = ['c:\\marmalade\\6.2\\modules\\iw2d\\iw2d.mkf', 'c:\\marmalade\\6.2\\modules\\iwgx\\iwgx.mkf', 'c:\\marmalade\\6.2\\modules\\iwgeom\\iwgeom.mkf', 'c:\\marmalade\\6.2\\modules\\iwutil\\iwutil.mkf', u'c:\\users\\1106786\\appdata\\roaming\\marmalade\\packages\\6.2.2\\libjpeg_6b\\libjpeg.mkf', u'c:\\users\\1106786\\appdata\\roaming\\marmalade\\packages\\6.2.2\\libpng_1.2.34\\libpng.mkf', u'c:\\users\\1106786\\appdata\\roaming\\marmalade\\packages\\6.2.2\\zlib_1.2.4\\zlib.mkf', 'c:\\marmalade\\6.2\\modules\\iwresmanager\\iwresmanager.mkf', 'c:\\marmalade\\6.2\\modules\\iwgl\\iwgl.mkf', 'c:\\marmalade\\6.2\\modules\\iwgxfont\\iwgxfont.mkf', u'c:\\users\\1106786\\appdata\\roaming\\marmalade\\packages\\6.2.2\\tiniconv_1.0.1\\tiniconv.mkf', 'c:\\users\\1106786\\dropbox\\dropbox\\pg life\\project impact\\code\\demos\\o-demo_8_magicdoor\\o-demo_8_magicdoor.mkf', 'c:\\users\\1106786\\dropbox\\dropbox\\pg life\\project impact\\code\\demos\\o-demo_8_magicdoor\\libs\\cjson-for-marmalade\\cjson.mkf', 'c:\\users\\1106786\\dropbox\\dropbox\\pg life\\project impact\\code\\demos\\o-demo_8_magicdoor\\libs\\soundengine\\soundengine.mkf']

class DeployConfig(object):
    pass

######### ASSET GROUPS #############

assets = {}

assets['Default'] = [
    ('c:/Users/1106786/Dropbox/Dropbox/PG life/Project Impact/Code/Demos/O-Demo_8_MagicDoor\data', '.', 0),
]

assets['default'] = [
    ('c:/users/1106786/dropbox/dropbox/pg life/project impact/code/demos/o-demo_8_magicdoor/data/splashscreen.jpg', 'splashscreen.jpg', 0),
    ('c:/users/1106786/dropbox/dropbox/pg life/project impact/code/demos/o-demo_8_magicdoor/data-ram/data-gles1/Level_1.group.bin,c:/users/1106786/dropbox/dropbox/pg life/project impact/code/demos/o-demo_8_magicdoor/data/Level_1.group.bin', 'Level_1.group.bin', 0),
]

assets['artbuild'] = [
    ('c:/users/1106786/dropbox/dropbox/pg life/project impact/code/demos/o-demo_8_magicdoor/data', '.', 0),
]

######### DEFAULT CONFIG #############

class DefaultConfig(DeployConfig):
    embed_icf = -1
    name = 'O-Demo_8_MagicDoor'
    pub_sign_key = 0
    priv_sign_key = 0
    caption = 'O-Demo_8_MagicDoor'
    long_caption = 'O-Demo_8_MagicDoor'
    version = [0, 0, 1]
    config = ['c:/Users/1106786/Dropbox/Dropbox/PG life/Project Impact/Code/Demos/O-Demo_8_MagicDoor/data/app.icf']
    data_dir = 'c:/Users/1106786/Dropbox/Dropbox/PG life/Project Impact/Code/Demos/O-Demo_8_MagicDoor/data'
    iphone_link_lib = []
    linux_ext_lib = []
    iphone_link_libdir = []
    iphone_link_opts = []
    osx_ext_dll = []
    android_external_jars = []
    android_external_res = []
    android_supports_gl_texture = []
    android_extra_manifest = []
    iphone_link_libdirs = []
    android_extra_application_manifest = []
    win32_ext_dll = []
    android_so = []
    iphone_link_libs = []
    target = {
         'arm' : {
                   'debug'   : r'c:/Users/1106786/Dropbox/Dropbox/PG life/Project Impact/Code/Demos/O-Demo_8_MagicDoor/build_o-demo_8_magicdoor_vc10/Debug_O_Demo_8_MagicDoor_VC10_arm/O-Demo_8_MagicDoor.s3e',
                   'release' : r'c:/Users/1106786/Dropbox/Dropbox/PG life/Project Impact/Code/Demos/O-Demo_8_MagicDoor/build_o-demo_8_magicdoor_vc10/Release_O_Demo_8_MagicDoor_VC10_arm/O-Demo_8_MagicDoor.s3e',
                 },
         'mips_gcc' : {
                   'debug'   : r'c:/Users/1106786/Dropbox/Dropbox/PG life/Project Impact/Code/Demos/O-Demo_8_MagicDoor/build_o-demo_8_magicdoor_vc10/Debug_O_Demo_8_MagicDoor_VC10_gcc_mips/O-Demo_8_MagicDoor.so',
                   'release' : r'c:/Users/1106786/Dropbox/Dropbox/PG life/Project Impact/Code/Demos/O-Demo_8_MagicDoor/build_o-demo_8_magicdoor_vc10/Release_O_Demo_8_MagicDoor_VC10_gcc_mips/O-Demo_8_MagicDoor.so',
                 },
         'x86' : {
                   'debug'   : r'c:/Users/1106786/Dropbox/Dropbox/PG life/Project Impact/Code/Demos/O-Demo_8_MagicDoor/build_o-demo_8_magicdoor_vc10/Debug_O_Demo_8_MagicDoor_VC10_x86/O-Demo_8_MagicDoor.s86',
                   'release' : r'c:/Users/1106786/Dropbox/Dropbox/PG life/Project Impact/Code/Demos/O-Demo_8_MagicDoor/build_o-demo_8_magicdoor_vc10/Release_O_Demo_8_MagicDoor_VC10_x86/O-Demo_8_MagicDoor.s86',
                 },
         'arm_gcc' : {
                   'debug'   : r'c:/Users/1106786/Dropbox/Dropbox/PG life/Project Impact/Code/Demos/O-Demo_8_MagicDoor/build_o-demo_8_magicdoor_vc10/Debug_O_Demo_8_MagicDoor_VC10_gcc_arm/O-Demo_8_MagicDoor.s3e',
                   'release' : r'c:/Users/1106786/Dropbox/Dropbox/PG life/Project Impact/Code/Demos/O-Demo_8_MagicDoor/build_o-demo_8_magicdoor_vc10/Release_O_Demo_8_MagicDoor_VC10_gcc_arm/O-Demo_8_MagicDoor.s3e',
                 },
        }
    assets = assets['Default']

default = DefaultConfig()
