# -*- coding: utf-8 -*-
# Deployment settings for Demo_2_Collision.
# This file is autogenerated by the mkb system and used by the s3e deployment
# tool during the build process.

config = {}
cmdline = ['c:/Marmalade/6.2/s3e/makefile_builder/mkb.py', '--use-temp-extension', '--verbose=1', 'c:/Users/1106786/Dropbox/Dropbox/PG life/Project Impact/Code/Demos/Demo_2_Collision/Demo_2_Collision.mkb', '--default-buildenv=vc10', '--msvc-project', '--deploy-only']
mkb = 'c:/Users/1106786/Dropbox/Dropbox/PG life/Project Impact/Code/Demos/Demo_2_Collision/Demo_2_Collision.mkb'
mkf = ['c:\\marmalade\\6.2\\modules\\iw2d\\iw2d.mkf', 'c:\\marmalade\\6.2\\modules\\iwgx\\iwgx.mkf', 'c:\\marmalade\\6.2\\modules\\iwgeom\\iwgeom.mkf', 'c:\\marmalade\\6.2\\modules\\iwutil\\iwutil.mkf', u'c:\\users\\1106786\\appdata\\roaming\\marmalade\\packages\\6.2.2\\libjpeg_6b\\libjpeg.mkf', u'c:\\users\\1106786\\appdata\\roaming\\marmalade\\packages\\6.2.2\\libpng_1.2.34\\libpng.mkf', u'c:\\users\\1106786\\appdata\\roaming\\marmalade\\packages\\6.2.2\\zlib_1.2.4\\zlib.mkf', 'c:\\marmalade\\6.2\\modules\\iwresmanager\\iwresmanager.mkf', 'c:\\marmalade\\6.2\\modules\\iwgl\\iwgl.mkf', 'c:\\marmalade\\6.2\\modules\\iwgxfont\\iwgxfont.mkf', u'c:\\users\\1106786\\appdata\\roaming\\marmalade\\packages\\6.2.2\\tiniconv_1.0.1\\tiniconv.mkf', 'c:\\users\\1106786\\dropbox\\dropbox\\pg life\\project impact\\code\\demos\\demo_2_collision\\demo_2_collision.mkf']

class DeployConfig(object):
    pass

######### ASSET GROUPS #############

assets = {}

assets['Default'] = [
    ('c:/Users/1106786/Dropbox/Dropbox/PG life/Project Impact/Code/Demos/Demo_2_Collision\data', '.', 0),
]

assets['default'] = [
    ('c:/users/1106786/dropbox/dropbox/pg life/project impact/code/demos/demo_2_collision/data/splashscreen.jpg', 'splashscreen.jpg', 0),
    ('c:/users/1106786/dropbox/dropbox/pg life/project impact/code/demos/demo_2_collision/data-ram/data-gles1/imgs.group.bin,c:/users/1106786/dropbox/dropbox/pg life/project impact/code/demos/demo_2_collision/data/imgs.group.bin', 'imgs.group.bin', 0),
]

assets['artbuild'] = [
    ('c:/users/1106786/dropbox/dropbox/pg life/project impact/code/demos/demo_2_collision/data', '.', 0),
]

######### DEFAULT CONFIG #############

class DefaultConfig(DeployConfig):
    embed_icf = -1
    name = 'mi'
    pub_sign_key = 0
    priv_sign_key = 0
    caption = 'mi'
    long_caption = 'mi'
    version = [0, 0, 1]
    config = ['c:/Users/1106786/Dropbox/Dropbox/PG life/Project Impact/Code/Demos/Demo_2_Collision/data/app.icf']
    data_dir = 'c:/Users/1106786/Dropbox/Dropbox/PG life/Project Impact/Code/Demos/Demo_2_Collision/data'
    iphone_link_lib = []
    linux_ext_lib = []
    iphone_link_libdir = []
    splashscreen = 'c:/Users/1106786/Dropbox/Dropbox/PG life/Project Impact/Code/Demos/Demo_2_Collision/data/splashscreen.jpg'
    iphone_link_opts = []
    osx_ext_dll = []
    android_external_jars = []
    android_external_res = []
    android_supports_gl_texture = []
    android_extra_manifest = []
    iphone_link_libdirs = []
    android_extra_application_manifest = []
    icon = 'c:/Users/1106786/Dropbox/Dropbox/PG life/Project Impact/Code/Demos/Demo_2_Collision/data/splashscreen.jpg'
    win32_ext_dll = []
    android_so = []
    iphone_link_libs = []
    target = {
         'arm' : {
                   'debug'   : r'c:/Users/1106786/Dropbox/Dropbox/PG life/Project Impact/Code/Demos/Demo_2_Collision/build_demo_2_collision_vc10/Debug_Demo_2_Collision_VC10_arm/Demo_2_Collision.s3e',
                   'release' : r'c:/Users/1106786/Dropbox/Dropbox/PG life/Project Impact/Code/Demos/Demo_2_Collision/build_demo_2_collision_vc10/Release_Demo_2_Collision_VC10_arm/Demo_2_Collision.s3e',
                 },
         'mips_gcc' : {
                   'debug'   : r'c:/Users/1106786/Dropbox/Dropbox/PG life/Project Impact/Code/Demos/Demo_2_Collision/build_demo_2_collision_vc10/Debug_Demo_2_Collision_VC10_gcc_mips/Demo_2_Collision.so',
                   'release' : r'c:/Users/1106786/Dropbox/Dropbox/PG life/Project Impact/Code/Demos/Demo_2_Collision/build_demo_2_collision_vc10/Release_Demo_2_Collision_VC10_gcc_mips/Demo_2_Collision.so',
                 },
         'x86' : {
                   'debug'   : r'c:/Users/1106786/Dropbox/Dropbox/PG life/Project Impact/Code/Demos/Demo_2_Collision/build_demo_2_collision_vc10/Debug_Demo_2_Collision_VC10_x86/Demo_2_Collision.s86',
                   'release' : r'c:/Users/1106786/Dropbox/Dropbox/PG life/Project Impact/Code/Demos/Demo_2_Collision/build_demo_2_collision_vc10/Release_Demo_2_Collision_VC10_x86/Demo_2_Collision.s86',
                 },
         'arm_gcc' : {
                   'debug'   : r'c:/Users/1106786/Dropbox/Dropbox/PG life/Project Impact/Code/Demos/Demo_2_Collision/build_demo_2_collision_vc10/Debug_Demo_2_Collision_VC10_gcc_arm/Demo_2_Collision.s3e',
                   'release' : r'c:/Users/1106786/Dropbox/Dropbox/PG life/Project Impact/Code/Demos/Demo_2_Collision/build_demo_2_collision_vc10/Release_Demo_2_Collision_VC10_gcc_arm/Demo_2_Collision.s3e',
                 },
        }
    assets = assets['Default']

default = DefaultConfig()
